version: "3"

services:
  nginx:
    image: nginx:latest
    configs:
      - source: vote.conf
        target: /etc/nginx/conf.d
  
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
  
  vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote:main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M
      
  worker:
    build:
      context: https://github.com/UffizziCloud/example-voting-worker:main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result:main
      dockerfile: Dockerfile

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 4h
  share_to_github: true

ingress:
  service: nginx
  port: 8080
