orbs:
  azure-acr: circleci/azure-acr@0.2.0
version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

workflows:
  build-deploy:
    jobs:
      - azure-acr/build-and-push-image:
          dockerfile: # defaults to `Dockerfile`
          path: # Defaults to working directory
          login-server-name: uffizziqa.azurecr.io # e.g. {yourregistryname}.azure.io
          registry-name: uffizziqa
          repo: https://uffizziqa.azurecr.io

jobs:
 build:
   machine: true

   steps:
     - checkout

     # build the application image
     - run: docker build -t uffizziqa/example-worker:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push uffizziqa/example-worker:$CIRCLE_BRANCH
